export const Countries = [
    //MAYBE: add Hong Kong, Greenland, Macau, Puerto Rico and other main territories or islands
    { label: 'Afghanistan (AFN)', value: 'Afghanistan' },
    { label: 'Albania (ALL)', value: 'Albania' },
    { label: 'Algeria (DZD)', value: 'Algeria' },
    { label: 'Andorra (EUR)', value: 'Andorra' },
    { label: 'Angola (AOA)', value: 'Angola' },
    { label: 'Antigua and Barbuda (XCD)', value: 'Antigua and Barbuda' },
    { label: 'Argentina (ARS)', value: 'Argentina' },
    { label: 'Armenia (AMD)', value: 'Armenia' },
    { label: 'Australia (AUD)', value: 'Australia' },
    { label: 'Austria (EUR)', value: 'Austria' },
    { label: 'Azerbaijan (AZN)', value: 'Azerbaijan' },
    { label: 'Bahamas (BSD)', value: 'Bahamas' },
    { label: 'Bahrain (BHD)', value: 'Bahrain' },
    { label: 'Bangladesh (BDT)', value: 'Bangladesh' },
    { label: 'Barbados (BBD)', value: 'Barbados' },
    { label: 'Belarus (BYN)', value: 'Belarus' },
    { label: 'Belgium (EUR)', value: 'Belgium' },
    { label: 'Belize (BZD)', value: 'Belize' },
    { label: 'Benin (XOF)', value: 'Benin' },
    { label: 'Bhutan (BTN)', value: 'Bhutan' },
    { label: 'Bolivia (BOB)', value: 'Bolivia' },
    { label: 'Bosnia and Herzegovina (BAM)', value: 'Bosnia and Herzegovina' },
    { label: 'Botswana (BWP)', value: 'Botswana' },
    { label: 'Brazil (BRL)', value: 'Brazil' },
    { label: 'Brunei (BND)', value: 'Brunei' },
    { label: 'Bulgaria (BGN)', value: 'Bulgaria' },
    { label: 'Burkina Faso (XOF)', value: 'Burkina Faso' },
    { label: 'Burundi (BIF)', value: 'Burundi' },
    { label: 'Cabo Verde (CVE)', value: 'Cabo Verde' },
    { label: 'Cambodia (KHR)', value: 'Cambodia' },
    { label: 'Cameroon (XAF)', value: 'Cameroon' },
    { label: 'Canada (CAD)', value: 'Canada' },
    { label: 'Central African Republic (XAF)', value: 'Central African Republic' },
    { label: 'Chad (XAF)', value: 'Chad' },
    { label: 'Chile (CLP)', value: 'Chile' },
    { label: 'China (CNY)', value: 'China' },
    { label: 'Colombia (COP)', value: 'Colombia' },
    { label: 'Comoros (KMF)', value: 'Comoros' },
    { label: 'Congo (Congo-Brazzaville) (XAF)', value: 'Congo (Congo-Brazzaville)' },
    { label: 'Costa Rica (CRC)', value: 'Costa Rica' },
    { label: 'Côte d\'Ivoire (XOF)', value: 'Côte d\'Ivoire' },
    { label: 'Croatia (EUR)', value: 'Croatia' },
    { label: 'Cuba (CUP)', value: 'Cuba' },
    { label: 'Cyprus (EUR)', value: 'Cyprus' },
    { label: 'Czechia (Czech Republic) (CZK)', value: 'Czechia (Czech Republic)' },
    { label: 'Democratic Republic of the Congo (CDF)', value: 'Democratic Republic of the Congo' }, //GET
    { label: 'Denmark (DKK)', value: 'Denmark' },
    { label: 'Djibouti (DJF)', value: 'Djibouti' },
    { label: 'Dominica (XCD)', value: 'Dominica' },
    { label: 'Dominican Republic (DOP)', value: 'Dominican Republic' },
    { label: 'Ecuador (USD)', value: 'Ecuador' },
    { label: 'Egypt (EGP)', value: 'Egypt' },
    { label: 'El Salvador (USD)', value: 'El Salvador' },
    { label: 'Equatorial Guinea (XAF)', value: 'Equatorial Guinea' },
    { label: 'Eritrea (ERN)', value: 'Eritrea' },
    { label: 'Estonia (EUR)', value: 'Estonia' },
    { label: 'Eswatini (SZL)', value: 'Eswatini' },
    { label: 'Ethiopia (ETB)', value: 'Ethiopia' },
    { label: 'Fiji (FJD)', value: 'Fiji' },
    { label: 'Finland (EUR)', value: 'Finland' },
    { label: 'France (EUR)', value: 'France' },
    { label: 'Gabon (XAF)', value: 'Gabon' },
    { label: 'Gambia (GMD)', value: 'Gambia' },
    { label: 'Georgia (GEL)', value: 'Georgia' },
    { label: 'Germany (EUR)', value: 'Germany' },
    { label: 'Ghana (GHS)', value: 'Ghana' },
    { label: 'Greece (EUR)', value: 'Greece' },
    { label: 'Grenada (XCD)', value: 'Grenada' },
    { label: 'Guatemala (GTQ)', value: 'Guatemala' },
    { label: 'Guinea (GNF)', value: 'Guinea' },
    { label: 'Guinea-Bissau (XOF)', value: 'Guinea-Bissau' },
    { label: 'Guyana (GYD)', value: 'Guyana' },
    { label: 'Haiti (HTG)', value: 'Haiti' },
    { label: 'Honduras (HNL)', value: 'Honduras' },
    { label: 'Hungary (HUF)', value: 'Hungary' },
    { label: 'Iceland (ISK)', value: 'Iceland' },
    { label: 'India (INR)', value: 'India' },
    { label: 'Indonesia (IDR)', value: 'Indonesia' },
    { label: 'Iran (IRR)', value: 'Iran' },
    { label: 'Iraq (IQD)', value: 'Iraq' },
    { label: 'Ireland (EUR)', value: 'Ireland' },
    { label: 'Israel (ILS)', value: 'Israel' },
    { label: 'Italy (EUR)', value: 'Italy' },
    { label: 'Jamaica (JMD)', value: 'Jamaica' },
    { label: 'Japan (JPY)', value: 'Japan' },
    { label: 'Jordan (JOD)', value: 'Jordan' },
    { label: 'Kazakhstan (KZT)', value: 'Kazakhstan' },
    { label: 'Kenya (KES)', value: 'Kenya' },
    { label: 'Kiribati (AUD)', value: 'Kiribati' },
    { label: 'Kosovo (EUR)', value: 'Kosovo' },
    { label: 'Kuwait (KWD)', value: 'Kuwait' },
    { label: 'Kyrgyzstan (KGS)', value: 'Kyrgyzstan' },
    { label: 'Laos (LAK)', value: 'Laos' },
    { label: 'Latvia (EUR)', value: 'Latvia' },
    { label: 'Lebanon (LBP)', value: 'Lebanon' },
    { label: 'Lesotho (LSL)', value: 'Lesotho' },
    { label: 'Liberia (LRD)', value: 'Liberia' },
    { label: 'Libya (LYD)', value: 'Libya' },
    { label: 'Liechtenstein (CHF)', value: 'Liechtenstein' },
    { label: 'Lithuania (EUR)', value: 'Lithuania' },
    { label: 'Luxembourg (EUR)', value: 'Luxembourg' },
    { label: 'Madagascar (MGA)', value: 'Madagascar' },
    { label: 'Malawi (MWK)', value: 'Malawi' },
    { label: 'Malaysia (MYR)', value: 'Malaysia' },
    { label: 'Maldives (MVR)', value: 'Maldives' },
    { label: 'Mali (XOF)', value: 'Mali' },
    { label: 'Malta (EUR)', value: 'Malta' },
    { label: 'Marshall Islands (USD)', value: 'Marshall Islands' },
    { label: 'Mauritania (MRU)', value: 'Mauritania' },
    { label: 'Mauritius (MUR)', value: 'Mauritius' },
    { label: 'Mexico (MXN)', value: 'Mexico' },
    { label: 'Micronesia (USD)', value: 'Micronesia' },
    { label: 'Moldova (MDL)', value: 'Moldova' },
    { label: 'Monaco (EUR)', value: 'Monaco' },
    { label: 'Mongolia (MNT)', value: 'Mongolia' },
    { label: 'Montenegro (EUR)', value: 'Montenegro' },
    { label: 'Morocco (MAD)', value: 'Morocco' },
    { label: 'Mozambique (MZN)', value: 'Mozambique' },
    { label: 'Myanmar (MMK)', value: 'Myanmar' },
    { label: 'Namibia (NAD)', value: 'Namibia' },
    { label: 'Nauru (AUD)', value: 'Nauru' },
    { label: 'Nepal (NPR)', value: 'Nepal' },
    { label: 'Netherlands (EUR)', value: 'Netherlands' },
    { label: 'New Zealand (NZD)', value: 'New Zealand' },
    { label: 'Nicaragua (NIO)', value: 'Nicaragua' },
    { label: 'Niger (XOF)', value: 'Niger' },
    { label: 'Nigeria (NGN)', value: 'Nigeria' },
    { label: 'North Korea (KPW)', value: 'North Korea' },
    { label: 'North Macedonia (MKD)', value: 'North Macedonia' },
    { label: 'Norway (NOK)', value: 'Norway' },
    { label: 'Oman (OMR)', value: 'Oman' },
    { label: 'Pakistan (PKR)', value: 'Pakistan' },
    { label: 'Palau (USD)', value: 'Palau' },
    { label: 'Palestine (ILS)', value: 'Palestine' },
    { label: 'Panama (USD)', value: 'Panama' },
    { label: 'Papua New Guinea (PGK)', value: 'Papua New Guinea' },
    { label: 'Paraguay (PYG)', value: 'Paraguay' },
    { label: 'Peru (PEN)', value: 'Peru' },
    { label: 'Philippines (PHP)', value: 'Philippines' },
    { label: 'Poland (PLN)', value: 'Poland' },
    { label: 'Portugal (EUR)', value: 'Portugal' },
    { label: 'Qatar (QAR)', value: 'Qatar' },
    { label: 'Romania (RON)', value: 'Romania' },
    { label: 'Russia (RUB)', value: 'Russia' },
    { label: 'Rwanda (RWF)', value: 'Rwanda' },
    { label: 'Saint Kitts and Nevis (XCD)', value: 'Saint Kitts and Nevis' },
    { label: 'Saint Lucia (XCD)', value: 'Saint Lucia' },
    { label: 'Saint Vincent and the Grenadines (XCD)', value: 'Saint Vincent and the Grenadines' },
    { label: 'Samoa (WST)', value: 'Samoa' },
    { label: 'San Marino (EUR)', value: 'San Marino' },
    { label: 'Sao Tome and Principe (STN)', value: 'Sao Tome and Principe' },
    { label: 'Saudi Arabia (SAR)', value: 'Saudi Arabia' },
    { label: 'Senegal (XOF)', value: 'Senegal' },
    { label: 'Serbia (RSD)', value: 'Serbia' },
    { label: 'Seychelles (SCR)', value: 'Seychelles' },
    { label: 'Sierra Leone (SLE)', value: 'Sierra Leone' },
    { label: 'Singapore (SGD)', value: 'Singapore' },
    { label: 'Slovakia (EUR)', value: 'Slovakia' },
    { label: 'Slovenia (EUR)', value: 'Slovenia' },
    { label: 'Solomon Islands (SBD)', value: 'Solomon Islands' },
    { label: 'Somalia (SOS)', value: 'Somalia' },
    { label: 'South Africa (ZAR)', value: 'South Africa' },
    { label: 'South Korea (KRW)', value: 'South Korea' },
    { label: 'South Sudan (SSP)', value: 'South Sudan' },
    { label: 'Spain (EUR)', value: 'Spain' },
    { label: 'Sri Lanka (LKR)', value: 'Sri Lanka' },
    { label: 'Sudan (SDG)', value: 'Sudan' },
    { label: 'Suriname (SRD)', value: 'Suriname' },
    { label: 'Sweden (SEK)', value: 'Sweden' },
    { label: 'Switzerland (CHF)', value: 'Switzerland' },
    { label: 'Syria (SYP)', value: 'Syria' },
    { label: 'Taiwan (TWD)', value: 'Taiwan' },
    { label: 'Tajikistan (TJS)', value: 'Tajikistan' },
    { label: 'Tanzania (TZS)', value: 'Tanzania' },
    { label: 'Thailand (THB)', value: 'Thailand' },
    { label: 'Timor-Leste (USD)', value: 'Timor-Leste' },
    { label: 'Togo (XOF)', value: 'Togo' },
    { label: 'Tonga (TOP)', value: 'Tonga' },
    { label: 'Trinidad and Tobago (TTD)', value: 'Trinidad and Tobago' },
    { label: 'Tunisia (TND)', value: 'Tunisia' },
    { label: 'Turkey (TRY)', value: 'Turkey' },
    { label: 'Turkmenistan (TMT)', value: 'Turkmenistan' },
    { label: 'Tuvalu (AUD)', value: 'Tuvalu' },
    { label: 'Uganda (UGX)', value: 'Uganda' },
    { label: 'Ukraine (UAH)', value: 'Ukraine' },
    { label: 'United Arab Emirates (UAE) (AED)', value: 'United Arab Emirates (UAE)' },
    { label: 'United Kingdom (UK) (GBP)', value: 'United Kingdom (UK)' },
    { label: 'United States of America (USA) (USD)', value: 'United States of America (USA)' },
    { label: 'Uruguay (UYU)', value: 'Uruguay' },
    { label: 'Uzbekistan (UZS)', value: 'Uzbekistan' },
    { label: 'Vanuatu (VUV)', value: 'Vanuatu' },
    { label: 'Vatican City (Holy See) (EUR)', value: 'Vatican City (Holy See)' },
    { label: 'Venezuela (VES)', value: 'Venezuela' },
    { label: 'Vietnam (VND)', value: 'Vietnam' },
    { label: 'Yemen (YER)', value: 'Yemen' },
    { label: 'Zambia (ZMW)', value: 'Zambia' },
    { label: 'Zimbabwe (USD)', value: 'Zimbabwe' },
    
];

//{ label: '', value: '' },

/*
Links for world currencies: 
https://www.countries-ofthe-world.com/world-currencies.html ***
https://openknowledge.fao.org/server/api/core/bitstreams/7d0c5832-7360-4f49-962d-ccf72338dc79/content
*/