import Flag from 'react-flagkit';
import "./Currency.css"; 
import Akrotiri from './img/Flag_of_the_Dhekelia_Garrison.svg'
import Ascension from './img/Flag_of_Ascension_Island.svg'
import Bonaire from './img/Flag_of_Bonaire.svg'
import Chatham from './img/Flag_of_Chatham_Islands.svg'
import Eswatini from './img/Flag_of_Eswatini.svg'
import Réunion from './img/Proposed_flag_of_Réunion_(VAR).svg'
import Eustatius from './img/Flag_of_Sint_Eustatius.svg'
import Wake from './img/Flag_of_Wake_Island.svg'

/*
World currencies sources: 
https://www.countries-ofthe-world.com/world-currencies.html
https://openknowledge.fao.org/server/api/core/bitstreams/7d0c5832-7360-4f49-962d-ccf72338dc79/content 
*/

//label is what's displayed as a dropdown option, value is what's passed as a parameter

export const Countries = [
    { label: <div id="flags"> <Flag country="AF"/> &ensp;Afghanistan </div>, value: 'Afghanistan (AFN)' },
    { label: <div id="flags"> <img id="img" src={Akrotiri} alt="Akrotiri and Dhekelia"/> &ensp;Akrotiri and Dhekelia </div>, value: 'Akrotiri and Dhekelia (EUR)'},
    { label: <div id="flags"> <Flag country="AX"/> &ensp;Aland Islands </div>, value: 'Aland Islands (EUR)' },
    { label: <div id="flags"> <Flag country="AL"/> &ensp;Albania </div>, value: 'Albania (ALL)' },
    { label: <div id="flags"> <Flag country="DZ"/> &ensp;Algeria </div>, value: 'Algeria (DZD)' },
    { label: <div id="flags"> <Flag country="AS"/> &ensp;American Samoa </div>, value: 'American Samoa (USD)' },
    { label: <div id="flags"> <Flag country="AD"/> &ensp;Andorra </div>, value: 'Andorra (EUR)' },
    { label: <div id="flags"> <Flag country="AO"/> &ensp;Angola </div>, value: 'Angola (AOA)' },
    { label: <div id="flags"> <Flag country="AI"/> &ensp;Anguilla </div>, value: 'Anguilla (XCD)' },
    { label: <div id="flags"> <Flag country="AG"/> &ensp;Antigua and Barbuda </div>, value: 'Antigua and Barbuda (XCD)' },
    { label: <div id="flags"> <Flag country="AR"/> &ensp;Argentina </div>, value: 'Argentina (ARS)' },
    { label: <div id="flags"> <Flag country="AM"/> &ensp;Armenia </div>, value: 'Armenia (AMD)' },
    { label: <div id="flags"> <Flag country="AW"/> &ensp;Aruba </div>, value: 'Aruba (AWG)' },
    { label: <div id="flags"> <img id="img" src={Ascension} alt="Ascension"/> &ensp;Ascension Island </div>, value: 'Ascension Island (SHP)' },
    { label: <div id="flags"> <Flag country="AU"/> &ensp;Australia </div>, value: 'Australia (AUD)' },
    { label: <div id="flags"> <Flag country="AT"/> &ensp;Austria </div>, value: 'Austria (EUR)' },
    { label: <div id="flags"> <img id="img" src="http://purecatamphetamine.github.io/country-flag-icons/3x2/AZ.svg" alt="Azerbaijan"/> &ensp;Azerbaijan </div>, value: 'Azerbaijan (AZN)' },
    { label: <div id="flags"> <Flag country="BS"/> &ensp;Bahamas </div>, value: 'Bahamas (BSD)' },
    { label: <div id="flags"> <Flag country="BH"/> &ensp;Bahrain </div>, value: 'Bahrain (BHD)' },
    { label: <div id="flags"> <Flag country="BD"/> &ensp;Bangladesh </div>, value: 'Bangladesh (BDT)' },
    { label: <div id="flags"> <Flag country="BB"/> &ensp;Barbados </div>, value: 'Barbados (BBD)' },
    { label: <div id="flags"> <Flag country="BY"/> &ensp;Belarus </div>, value: 'Belarus (BYN)' },
    { label: <div id="flags"> <Flag country="BE"/> &ensp;Belgium </div>, value: 'Belgium (EUR)' },
    { label: <div id="flags"> <Flag country="BZ"/> &ensp;Belize </div>, value: 'Belize (BZD)' },
    { label: <div id="flags"> <Flag country="BJ"/> &ensp;Benin </div>, value: 'Benin (XOF)' },
    { label: <div id="flags"> <Flag country="BM"/> &ensp;Bermuda </div>, value: 'Bermuda (BMD)' },
    { label: <div id="flags"> <Flag country="BT"/> &ensp;Bhutan </div>, value: 'Bhutan (BTN)' },
    { label: <div id="flags"> <Flag country="BO"/> &ensp;Bolivia </div>, value: 'Bolivia (BOB)' },
    { label: <div id="flags"> <img id="img" src={Bonaire} alt="Bonaire" /> &ensp;Bonaire </div>, value: 'Bonaire (USD)' },
    { label: <div id="flags"> <Flag country="BA"/> &ensp;Bosnia and Herzegovina </div>, value: 'Bosnia and Herzegovina (BAM)' },
    { label: <div id="flags"> <Flag country="BW"/> &ensp;Botswana </div>, value: 'Botswana (BWP)' },
    { label: <div id="flags"> <Flag country="BR"/> &ensp;Brazil </div>, value: 'Brazil (BRL)' },
    { label: <div id="flags"> <Flag country="IO"/> &ensp;British Indian Ocean Territory </div>, value: 'British Indian Ocean Territory (USD)' },
    { label: <div id="flags"> <Flag country="VG"/> &ensp;British Virgin Islands </div>, value: 'British Virgin Islands (USD)' },
    { label: <div id="flags"> <Flag country="BN"/> &ensp;Brunei </div>, value: 'Brunei (BND)' },
    { label: <div id="flags"> <Flag country="BG"/> &ensp;Bulgaria </div>, value: 'Bulgaria (BGN)' },
    { label: <div id="flags"> <Flag country="BF"/> &ensp;Burkina Faso </div>, value: 'Burkina Faso (XOF)' },
    { label: <div id="flags"> <Flag country="BI"/> &ensp;Burundi </div>, value: 'Burundi (BIF)' },
    { label: <div id="flags"> <Flag country="CV"/> &ensp;Cabo Verde </div>, value: 'Cabo Verde (CVE)' },
    { label: <div id="flags"> <Flag country="KH"/> &ensp;Cambodia </div>, value: 'Cambodia (KHR)' },
    { label: <div id="flags"> <Flag country="CM"/> &ensp;Cameroon </div>, value: 'Cameroon (XAF)' },
    { label: <div id="flags"> <Flag country="CA"/> &ensp;Canada </div>, value: 'Canada (CAD)' },
    { label: <div id="flags"> <Flag country="NL"/> &ensp;Caribbean Netherlands </div>, value: 'Caribbean Netherlands (USD)' },
    { label: <div id="flags"> <Flag country="KY"/> &ensp;Cayman Islands </div>, value: 'Cayman Islands (KYD)' },
    { label: <div id="flags"> <Flag country="CF"/> &ensp;Central African Republic </div>, value: 'Central African Republic (XAF)' },
    { label: <div id="flags"> <Flag country="TD"/> &ensp;Chad </div>, value: 'Chad (XAF)' },
    { label: <div id="flags"> <img id="img" src={Chatham} alt="Chatham" /> &ensp;Chatham Islands </div>, value: 'Chatham Islands (NZD)' },
    { label: <div id="flags"> <Flag country="CL"/> &ensp;Chile </div>, value: 'Chile (CLP)' },
    { label: <div id="flags"> <Flag country="CN"/> &ensp;China </div>, value: 'China (CNY)' },
    { label: <div id="flags"> <Flag country="CX"/> &ensp;Christmas Island  </div>, value: 'Christmas Island (AUD)' },
    { label: <div id="flags"> <Flag country="CC"/> &ensp;Cocos (Keeling) Islands </div>, value: 'Cocos (Keeling) Islands (AUD)' },
    { label: <div id="flags"> <Flag country="CO"/> &ensp;Colombia </div>, value: 'Colombia (COP)' },
    { label: <div id="flags"> <Flag country="KM"/> &ensp;Comoros </div>, value: 'Comoros (KMF)' },
    { label: <div id="flags"> <img id="img" src="http://purecatamphetamine.github.io/country-flag-icons/3x2/CG.svg" alt="Congo"/> &ensp;Congo (Congo-Brazzaville) </div>, value: 'Congo (Congo-Brazzaville) (XAF)' },
    { label: <div id="flags"> <Flag country="CK"/> &ensp;Cook Islands </div>, value: 'Cook Islands (NZD)' },
    { label: <div id="flags"> <Flag country="CR"/> &ensp;Costa Rica </div>, value: 'Costa Rica (CRC)' },
    { label: <div id="flags"> <Flag country="CI"/> &ensp;Côte d'Ivoire </div>, value: 'Côte d\'Ivoire (XOF)' },
    { label: <div id="flags"> <Flag country="HR"/> &ensp;Croatia </div>, value: 'Croatia (EUR)' },
    { label: <div id="flags"> <Flag country="CU"/> &ensp;Cuba </div>, value: 'Cuba (CUP)' },
    { label: <div id="flags"> <Flag country="CW"/> &ensp;Curaçao </div>, value: 'Curaçao (ANG)' },
    { label: <div id="flags"> <Flag country="CY"/> &ensp;Cyprus </div>, value: 'Cyprus (EUR)' },
    { label: <div id="flags"> <Flag country="CZ"/> &ensp;Czechia (Czech Republic) </div>, value: 'Czechia (Czech Republic) (CZK)' },
    { label: <div id="flags"> <img id="img" src="http://purecatamphetamine.github.io/country-flag-icons/3x2/CD.svg" alt="DRC"/> &ensp;Democratic Republic of the Congo </div>, value: 'Democratic Republic of the Congo (CDF)' }, //GET
    { label: <div id="flags"> <Flag country="DK"/> &ensp;Denmark </div>, value: 'Denmark (DKK)' },
    { label: <div id="flags"> <Flag country="DJ"/> &ensp;Djibouti </div>, value: 'Djibouti (DJF)' },
    { label: <div id="flags"> <Flag country="DM"/> &ensp;Dominica </div>, value: 'Dominica (XCD)' },
    { label: <div id="flags"> <Flag country="DO"/> &ensp;Dominican Republic </div>, value: 'Dominican Republic (DOP)' },
    { label: <div id="flags"> <Flag country="EC"/> &ensp;Ecuador </div>, value: 'Ecuador (USD)' },
    { label: <div id="flags"> <Flag country="EG"/> &ensp;Egypt </div>, value: 'Egypt (EGP)' },
    { label: <div id="flags"> <Flag country="SV"/> &ensp;El Salvador </div>, value: 'El Salvador (USD)' },
    { label: <div id="flags"> <Flag country="GQ"/> &ensp;Equatorial Guinea </div>, value: 'Equatorial Guinea (XAF)' },
    { label: <div id="flags"> <Flag country="ER"/> &ensp;Eritrea </div>, value: 'Eritrea (ERN)' },
    { label: <div id="flags"> <Flag country="EE"/> &ensp;Estonia </div>, value: 'Estonia (EUR)' },
    { label: <div id="flags"> <img id="img" src={Eswatini} alt="Eswatini" /> &ensp;Eswatini </div>, value: 'Eswatini (SZL)' },
    { label: <div id="flags"> <Flag country="ET"/> &ensp;Ethiopia </div>, value: 'Ethiopia (ETB)' },
    { label: <div id="flags"> <Flag country="FK"/> &ensp;Falkland Islands </div>, value: 'Falkland Islands (FKP)' },
    { label: <div id="flags"> <Flag country="FO"/> &ensp;Faroe Islands </div>, value: 'Faroe Islands (DKK)' },
    { label: <div id="flags"> <Flag country="FJ"/> &ensp;Fiji </div>, value: 'Fiji (FJD)' },
    { label: <div id="flags"> <Flag country="FI"/> &ensp;Finland </div>, value: 'Finland (EUR)' },
    { label: <div id="flags"> <Flag country="FR"/> &ensp;France </div>, value: 'France (EUR)' },
    { label: <div id="flags"> <Flag country="GF"/> &ensp;French Guiana </div>, value: 'French Guiana (EUR)' },
    { label: <div id="flags"> <Flag country="PF"/> &ensp;French Polynesia </div>, value: 'French Polynesia (XPF)' },
    { label: <div id="flags"> <Flag country="GA"/> &ensp;Gabon </div>, value: 'Gabon (XAF)' },
    { label: <div id="flags"> <Flag country="GM"/> &ensp;Gambia </div>, value: 'Gambia (GMD)' },
    { label: <div id="flags"> <Flag country="GE"/> &ensp;Georgia </div>, value: 'Georgia (GEL)' },
    { label: <div id="flags"> <Flag country="DE"/> &ensp;Germany </div>, value: 'Germany (EUR)' },
    { label: <div id="flags"> <Flag country="GH"/> &ensp;Ghana </div>, value: 'Ghana (GHS)' },
    { label: <div id="flags"> <Flag country="GI"/> &ensp;Gibraltar </div>, value: 'Gibraltar (GIP)' },
    { label: <div id="flags"> <Flag country="GR"/> &ensp;Greece </div>, value: 'Greece (EUR)' },
    { label: <div id="flags"> <Flag country="GL"/> &ensp;Greenland </div>, value: 'Greenland (DKK)' },
    { label: <div id="flags"> <Flag country="GD"/> &ensp;Grenada </div>, value: 'Grenada (XCD)' },
    { label: <div id="flags"> <Flag country="GP"/> &ensp;Guadeloupe </div>, value: 'Guadeloupe (EUR)' },
    { label: <div id="flags"> <Flag country="GU"/> &ensp;Guam </div>, value: 'Guam (USD)' },
    { label: <div id="flags"> <Flag country="GT"/> &ensp;Guatemala </div>, value: 'Guatemala (GTQ)' },
    { label: <div id="flags"> <Flag country="GG"/> &ensp;Guernsey </div>, value: 'Guernsey (GGP)' },
    { label: <div id="flags"> <Flag country="GN"/> &ensp;Guinea </div>, value: 'Guinea (GNF)' },
    { label: <div id="flags"> <Flag country="GW"/> &ensp;Guinea-Bissau </div>, value: 'Guinea-Bissau (XOF)' },
    { label: <div id="flags"> <Flag country="GY"/> &ensp;Guyana </div>, value: 'Guyana (GYD)' },
    { label: <div id="flags"> <Flag country="HT"/> &ensp;Haiti </div>, value: 'Haiti (HTG)' },
    { label: <div id="flags"> <Flag country="HN"/> &ensp;Honduras </div>, value: 'Honduras (HNL)' },
    { label: <div id="flags"> <Flag country="HK"/> &ensp;Hong Kong </div>, value: 'Hong Kong (HKD)' },
    { label: <div id="flags"> <Flag country="HU"/> &ensp;Hungary </div>, value: 'Hungary (HUF)' },
    { label: <div id="flags"> <Flag country="IS"/> &ensp;Iceland </div>, value: 'Iceland (ISK)' },
    { label: <div id="flags"> <Flag country="IN"/> &ensp;India </div>, value: 'India (INR)' },
    { label: <div id="flags"> <Flag country="ID"/> &ensp;Indonesia </div>, value: 'Indonesia (IDR)' },
    { label: <div id="flags"> <Flag country="IR"/> &ensp;Iran </div>, value: 'Iran (IRR)' },
    { label: <div id="flags"> <Flag country="IQ"/> &ensp;Iraq </div>, value: 'Iraq (IQD)' },
    { label: <div id="flags"> <Flag country="IE"/> &ensp;Ireland </div>, value: 'Ireland (EUR)' },
    { label: <div id="flags"> <Flag country="IM"/> &ensp;Isle of Man </div>, value: 'Isle of Man (IMP)' },
    { label: <div id="flags"> <Flag country="IL"/> &ensp;Israel </div>, value: 'Israel (ILS)' },
    { label: <div id="flags"> <Flag country="IT"/> &ensp;Italy </div>, value: 'Italy (EUR)' },
    { label: <div id="flags"> <Flag country="JM"/> &ensp;Jamaica </div>, value: 'Jamaica (JMD)' },
    { label: <div id="flags"> <Flag country="JP"/> &ensp;Japan </div>, value: 'Japan (JPY)' },
    { label: <div id="flags"> <Flag country="JE"/> &ensp;Jersey </div>, value: 'Jersey (JEP)' },
    { label: <div id="flags"> <Flag country="JO"/> &ensp;Jordan </div>, value: 'Jordan (JOD)' },
    { label: <div id="flags"> <Flag country="KZ"/> &ensp;Kazakhstan </div>, value: 'Kazakhstan (KZT)' },
    { label: <div id="flags"> <Flag country="KE"/> &ensp;Kenya </div>, value: 'Kenya (KES)' },
    { label: <div id="flags"> <Flag country="KI"/> &ensp;Kiribati </div>, value: 'Kiribati (AUD)' },
    { label: <div id="flags"> <Flag country="XK"/> &ensp;Kosovo </div>, value: 'Kosovo (EUR)' },
    { label: <div id="flags"> <Flag country="KW"/> &ensp;Kuwait </div>, value: 'Kuwait (KWD)' },
    { label: <div id="flags"> <Flag country="KG"/> &ensp;Kyrgyzstan </div>, value: 'Kyrgyzstan (KGS)' },
    { label: <div id="flags"> <Flag country="LA"/> &ensp;Laos </div>, value: 'Laos (LAK)' },
    { label: <div id="flags"> <Flag country="LV"/> &ensp;Latvia </div>, value: 'Latvia (EUR)' },
    { label: <div id="flags"> <Flag country="LB"/> &ensp;Lebanon </div>, value: 'Lebanon (LBP)' },
    { label: <div id="flags"> <Flag country="LS"/> &ensp;Lesotho </div>, value: 'Lesotho (LSL)' },
    { label: <div id="flags"> <Flag country="LR"/> &ensp;Liberia </div>, value: 'Liberia (LRD)' },
    { label: <div id="flags"> <Flag country="LY"/> &ensp;Libya </div>, value: 'Libya (LYD)' },
    { label: <div id="flags"> <Flag country="LI"/> &ensp;Liechtenstein </div>, value: 'Liechtenstein (CHF)' },
    { label: <div id="flags"> <Flag country="LT"/> &ensp;Lithuania </div>, value: 'Lithuania (EUR)' },
    { label: <div id="flags"> <Flag country="LU"/> &ensp;Luxembourg </div>, value: 'Luxembourg (EUR)' },
    { label: <div id="flags"> <Flag country="MO"/> &ensp;Macau </div>, value: 'Macau (MOP)' },
    { label: <div id="flags"> <Flag country="MG"/> &ensp;Madagascar </div>, value: 'Madagascar (MGA)' },
    { label: <div id="flags"> <Flag country="MW"/> &ensp;Malawi </div>, value: 'Malawi (MWK)' },
    { label: <div id="flags"> <Flag country="MY"/> &ensp;Malaysia </div>, value: 'Malaysia (MYR)' },
    { label: <div id="flags"> <Flag country="MV"/> &ensp;Maldives </div>, value: 'Maldives (MVR)' },
    { label: <div id="flags"> <Flag country="ML"/> &ensp;Mali </div>, value: 'Mali (XOF)' },
    { label: <div id="flags"> <Flag country="MT"/> &ensp;Malta </div>, value: 'Malta (EUR)' },
    { label: <div id="flags"> <Flag country="MH"/> &ensp;Marshall Islands </div>, value: 'Marshall Islands (USD)' },
    { label: <div id="flags"> <Flag country="MQ"/> &ensp;Martinique </div>, value: 'Martinique (EUR)' },
    { label: <div id="flags"> <Flag country="MR"/> &ensp;Mauritania </div>, value: 'Mauritania (MRU)' },
    { label: <div id="flags"> <Flag country="MU"/> &ensp;Mauritius </div>, value: 'Mauritius (MUR)' },
    { label: <div id="flags"> <Flag country="YT"/> &ensp;Mayotte </div>, value: 'Mayotte (EUR)' },
    { label: <div id="flags"> <Flag country="MX"/> &ensp;Mexico </div>, value: 'Mexico (MXN)' },
    { label: <div id="flags"> <Flag country="FM"/> &ensp;Micronesia </div>, value: 'Micronesia (USD)' },
    { label: <div id="flags"> <Flag country="MD"/> &ensp;Moldova </div>, value: 'Moldova (MDL)' },
    { label: <div id="flags"> <Flag country="MC"/> &ensp;Monaco </div>, value: 'Monaco (EUR)' },
    { label: <div id="flags"> <Flag country="MN"/> &ensp;Mongolia </div>, value: 'Mongolia (MNT)' },
    { label: <div id="flags"> <Flag country="ME"/> &ensp;Montenegro </div>, value: 'Montenegro (EUR)' },
    { label: <div id="flags"> <Flag country="MS"/> &ensp;Montserrat </div>, value: 'Montserrat (XCD)' },
    { label: <div id="flags"> <Flag country="MA"/> &ensp;Morocco </div>, value: 'Morocco (MAD)' },
    { label: <div id="flags"> <Flag country="MZ"/> &ensp;Mozambique </div>, value: 'Mozambique (MZN)' },
    { label: <div id="flags"> <Flag country="MM"/> &ensp;Myanmar </div>, value: 'Myanmar (MMK)' },
    { label: <div id="flags"> <img id="img" src="http://purecatamphetamine.github.io/country-flag-icons/3x2/NA.svg" alt="Namibia"/> &ensp;Namibia </div>, value: 'Namibia (NAD)' },
    { label: <div id="flags"> <Flag country="NR"/> &ensp;Nauru </div>, value: 'Nauru (AUD)' },
    { label: <div id="flags"> <Flag country="NP"/> &ensp;Nepal </div>, value: 'Nepal (NPR)' },
    { label: <div id="flags"> <Flag country="NL"/> &ensp;Netherlands </div>, value: 'Netherlands (EUR)' },
    { label: <div id="flags"> <Flag country="NC"/> &ensp;New Caledonia </div>, value: 'New Caledonia (XPF)' },
    { label: <div id="flags"> <Flag country="NZ"/> &ensp;New Zealand </div>, value: 'New Zealand (NZD)' },
    { label: <div id="flags"> <Flag country="NI"/> &ensp;Nicaragua </div>, value: 'Nicaragua (NIO)' },
    { label: <div id="flags"> <Flag country="NE"/> &ensp;Niger </div>, value: 'Niger (XOF)' },
    { label: <div id="flags"> <Flag country="NG"/> &ensp;Nigeria </div>, value: 'Nigeria (NGN)' },
    { label: <div id="flags"> <Flag country="NU"/> &ensp;Niue </div>, value: 'Niue (NZD)' },
    { label: <div id="flags"> <Flag country="NF"/> &ensp;Norfolk Island </div>, value: 'Norfolk Island (AUD)' },
    { label: <div id="flags"> <Flag country="MP"/> &ensp;Northern Mariana Islands </div>, value: 'Northern Mariana Islands (USD)' },
    { label: <div id="flags"> <Flag country="KP"/> &ensp;North Korea </div>, value: 'North Korea (KPW)' },
    { label: <div id="flags"> <Flag country="MK"/> &ensp;North Macedonia </div>, value: 'North Macedonia (MKD)' },
    { label: <div id="flags"> <Flag country="NO"/> &ensp;Norway </div>, value: 'Norway (NOK)' },
    { label: <div id="flags"> <Flag country="OM"/> &ensp;Oman </div>, value: 'Oman (OMR)' },
    { label: <div id="flags"> <Flag country="PK"/> &ensp;Pakistan </div>, value: 'Pakistan (PKR)' },
    { label: <div id="flags"> <Flag country="PW"/> &ensp;Palau </div>, value: 'Palau (USD)' },
    { label: <div id="flags"> <Flag country="PS"/> &ensp;Palestine </div>, value: 'Palestine (ILS)' },
    { label: <div id="flags"> <Flag country="PA"/> &ensp;Panama </div>, value: 'Panama (USD)' },
    { label: <div id="flags"> <Flag country="PG"/> &ensp;Papua New Guinea </div>, value: 'Papua New Guinea (PGK)' },
    { label: <div id="flags"> <Flag country="PY"/> &ensp;Paraguay </div>, value: 'Paraguay (PYG)' },
    { label: <div id="flags"> <Flag country="PE"/> &ensp;Peru </div>, value: 'Peru (PEN)' },
    { label: <div id="flags"> <Flag country="PH"/> &ensp;Philippines </div>, value: 'Philippines (PHP)' },
    { label: <div id="flags"> <Flag country="PN"/> &ensp;Pitcairn Islands </div>, value: 'Pitcairn Islands (NZD)' },
    { label: <div id="flags"> <Flag country="PL"/> &ensp;Poland </div>, value: 'Poland (PLN)' },
    { label: <div id="flags"> <Flag country="PT"/> &ensp;Portugal </div>, value: 'Portugal (EUR)' },
    { label: <div id="flags"> <Flag country="PR"/> &ensp;Puerto Rico </div>, value: 'Puerto Rico (USD)' },
    { label: <div id="flags"> <Flag country="QA"/> &ensp;Qatar </div>, value: 'Qatar (QAR)' },
    { label: <div id="flags"> <img id="img" src={Réunion} alt="Réunion" /> &ensp;Réunion </div>, value: 'Réunion (EUR)' },
    { label: <div id="flags"> <Flag country="RO"/> &ensp;Romania </div>, value: 'Romania (RON)' },
    { label: <div id="flags"> <Flag country="RU"/> &ensp;Russia </div>, value: 'Russia (RUB)' },
    { label: <div id="flags"> <Flag country="RW"/> &ensp;Rwanda </div>, value: 'Rwanda (RWF)' },
    { label: <div id="flags"> <img id="img" src="https://upload.wikimedia.org/wikipedia/commons/5/5a/Flag_of_Saba.svg" alt="Saba" /> &ensp;Saba </div>, value: 'Saba (USD)' },
    { label: <div id="flags"> <Flag country="BL"/> &ensp;Saint Barthélemy </div>, value: 'Saint Barthélemy (EUR)' },
    { label: <div id="flags"> <img id="img" src="http://purecatamphetamine.github.io/country-flag-icons/3x2/SH.svg" alt="St. Helena"/> &ensp;Saint Helena </div>, value: 'Saint Helena (SHP)' },
    { label: <div id="flags"> <img id="img" src="http://purecatamphetamine.github.io/country-flag-icons/3x2/KN.svg" alt="Saint Kitts"/> &ensp;Saint Kitts and Nevis </div>, value: 'Saint Kitts and Nevis (XCD)' },
    { label: <div id="flags"> <Flag country="LC"/> &ensp;Saint Lucia </div>, value: 'Saint Lucia (XCD)' },
    { label: <div id="flags"> <img id="img" src="http://purecatamphetamine.github.io/country-flag-icons/3x2/MF.svg" alt="St. Martin"/> &ensp;Saint Martin </div>, value: 'Saint Martin (EUR)' },
    { label: <div id="flags"> <Flag country="PM"/> &ensp;Saint Pierre and Miquelon </div>, value: 'Saint Pierre and Miquelon (EUR)' },
    { label: <div id="flags"> <Flag country="VC"/> &ensp;Saint Vincent and the Grenadines </div>, value: 'Saint Vincent and the Grenadines (XCD)' },
    { label: <div id="flags"> <Flag country="WS"/> &ensp;Samoa </div>, value: 'Samoa (WST)' },
    { label: <div id="flags"> <Flag country="SM"/> &ensp;San Marino </div>, value: 'San Marino (EUR)' },
    { label: <div id="flags"> <Flag country="ST"/> &ensp;São Tomé and Principe </div>, value: 'São Tomé and Principe (STN)' },
    { label: <div id="flags"> <Flag country="SA"/> &ensp;Saudi Arabia </div>, value: 'Saudi Arabia (SAR)' },
    { label: <div id="flags"> <Flag country="SN"/> &ensp;Senegal </div>, value: 'Senegal (XOF)' },
    { label: <div id="flags"> <Flag country="RS"/> &ensp;Serbia </div>, value: 'Serbia (RSD)' },
    { label: <div id="flags"> <Flag country="SC"/> &ensp;Seychelles </div>, value: 'Seychelles (SCR)' },
    { label: <div id="flags"> <Flag country="SL"/> &ensp;Sierra Leone </div>, value: 'Sierra Leone (SLE)' },
    { label: <div id="flags"> <Flag country="SG"/> &ensp;Singapore </div>, value: 'Singapore (SGD)' },
    { label: <div id="flags"> <img id="img" src={Eustatius} alt="Eustatius" /> &ensp;Sint Eustatius </div>, value: 'Sint Eustatius (USD)' },
    { label: <div id="flags"> <Flag country="SX"/> &ensp;Sint Maarten </div>, value: 'Sint Maarten (ANG)' },
    { label: <div id="flags"> <Flag country="SK"/> &ensp;Slovakia </div>, value: 'Slovakia (EUR)' },
    { label: <div id="flags"> <Flag country="SI"/> &ensp;Slovenia </div>, value: 'Slovenia (EUR)' },
    { label: <div id="flags"> <Flag country="SB"/> &ensp;Solomon Islands </div>, value: 'Solomon Islands (SBD)' },
    { label: <div id="flags"> <Flag country="SO"/> &ensp;Somalia </div>, value: 'Somalia (SOS)' },
    { label: <div id="flags"> <Flag country="ZA"/> &ensp;South Africa </div>, value: 'South Africa (ZAR)' },
    { label: <div id="flags"> <Flag country="GS"/> &ensp;South Georgia Island </div>, value: 'South Georgia Island (GBP)' },
    { label: <div id="flags"> <Flag country="KR"/> &ensp;South Korea </div>, value: 'South Korea (KRW)' },
    { label: <div id="flags"> <Flag country="SS"/> &ensp;South Sudan </div>, value: 'South Sudan (SSP)' },
    { label: <div id="flags"> <Flag country="ES"/> &ensp;Spain </div>, value: 'Spain (EUR)' },
    { label: <div id="flags"> <Flag country="LK"/> &ensp;Sri Lanka </div>, value: 'Sri Lanka (LKR)' },
    { label: <div id="flags"> <Flag country="SD"/> &ensp;Sudan </div>, value: 'Sudan (SDG)' },
    { label: <div id="flags"> <Flag country="SR"/> &ensp;Suriname </div>, value: 'Suriname (SRD)' },
    { label: <div id="flags"> <Flag country="SJ"/> &ensp;Svalbard and Jan Mayen </div>, value: 'Svalbard and Jan Mayen (NOK)' },
    { label: <div id="flags"> <Flag country="SE"/> &ensp;Sweden </div>, value: 'Sweden (SEK)' },
    { label: <div id="flags"> <Flag country="CH"/> &ensp;Switzerland </div>, value: 'Switzerland (CHF)' },
    { label: <div id="flags"> <Flag country="SY"/> &ensp;Syria </div>, value: 'Syria (SYP)' },
    { label: <div id="flags"> <Flag country="TW"/> &ensp;Taiwan </div>, value: 'Taiwan (TWD)' },
    { label: <div id="flags"> <Flag country="TJ"/> &ensp;Tajikistan </div>, value: 'Tajikistan (TJS)' },
    { label: <div id="flags"> <img id="img" src="http://purecatamphetamine.github.io/country-flag-icons/3x2/TZ.svg" alt="Tanzania"/> &ensp;Tanzania </div>, value: 'Tanzania (TZS)' },
    { label: <div id="flags"> <Flag country="TH"/> &ensp;Thailand </div>, value: 'Thailand (THB)' },
    { label: <div id="flags"> <Flag country="TL"/> &ensp;Timor-Leste </div>, value: 'Timor-Leste (USD)' },
    { label: <div id="flags"> <Flag country="TG"/> &ensp;Togo </div>, value: 'Togo (XOF)' },
    { label: <div id="flags"> <Flag country="TK"/> &ensp;Tokelau </div>, value: 'Tokelau (NZD)' },
    { label: <div id="flags"> <Flag country="TO"/> &ensp;Tonga </div>, value: 'Tonga (TOP)' },
    { label: <div id="flags"> <img id="img" src="http://purecatamphetamine.github.io/country-flag-icons/3x2/TT.svg" alt="Trinidad"/> &ensp;Trinidad and Tobago </div>, value: 'Trinidad and Tobago (TTD)' },
    { label: <div id="flags"> <img id="img" src="https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Tristan_da_Cunha.svg" alt="Tristan" /> &ensp;Tristan da Cunha </div>, value: 'Tristan da Cunha (GBP)' },
    { label: <div id="flags"> <Flag country="TN"/> &ensp;Tunisia </div>, value: 'Tunisia (TND)' },
    { label: <div id="flags"> <Flag country="TR"/> &ensp;Turkey </div>, value: 'Turkey (TRY)' },
    { label: <div id="flags"> <Flag country="TM"/> &ensp;Turkmenistan </div>, value: 'Turkmenistan (TMT)' },
    { label: <div id="flags"> <Flag country="TC"/> &ensp;Turks and Caicos Islands </div>, value: 'Turks and Caicos Islands (USD)' },    
    { label: <div id="flags"> <Flag country="TV"/> &ensp;Tuvalu </div>, value: 'Tuvalu (AUD)' },
    { label: <div id="flags"> <Flag country="UG"/> &ensp;Uganda </div>, value: 'Uganda (UGX)' },
    { label: <div id="flags"> <Flag country="UA"/> &ensp;Ukraine </div>, value: 'Ukraine (UAH)' },
    { label: <div id="flags"> <Flag country="AE"/> &ensp;United Arab Emirates (UAE) </div>, value: 'United Arab Emirates (UAE) (AED)' },
    { label: <div id="flags"> <Flag country="GB"/> &ensp;United Kingdom (UK) </div>, value: 'United Kingdom (UK) (GBP)' },
    { label: <div id="flags"> <Flag country="US"/> &ensp;United States of America (USA) </div>, value: 'United States of America (USA) (USD)' },
    { label: <div id="flags"> <Flag country="UY"/> &ensp;Uruguay </div>, value: 'Uruguay (UYU)' },
    { label: <div id="flags"> <Flag country="VI"/> &ensp;US Virgin Islands </div>, value: 'US Virgin Islands (USD)' },
    { label: <div id="flags"> <Flag country="UZ"/> &ensp;Uzbekistan </div>, value: 'Uzbekistan (UZS)' },
    { label: <div id="flags"> <Flag country="VU"/> &ensp;Vanuatu </div>, value: 'Vanuatu (VUV)' },
    { label: <div id="flags"> <Flag country="VA"/> &ensp;Vatican City (Holy See) </div>, value: 'Vatican City (Holy See) (EUR)' },
    { label: <div id="flags"> <Flag country="VE"/> &ensp;Venezuela </div>, value: 'Venezuela (VES)' },
    { label: <div id="flags"> <Flag country="VN"/> &ensp;Vietnam </div>, value: 'Vietnam (VND)' },
    { label: <div id="flags"> <img id="img" src={Wake} alt="Wake Is." /> &ensp;Wake Island </div>, value: 'Wake Island (USD)' },
    { label: <div id="flags"> <img id="img" src="https://upload.wikimedia.org/wikipedia/commons/d/d2/Flag_of_Wallis_and_Futuna.svg" alt="Wallis" /> &ensp;Wallis and Futuna </div>, value: 'Wallis and Futuna (XPF)' },
    { label: <div id="flags"> <Flag country="YE"/> &ensp;Yemen </div>, value: 'Yemen (YER)' },
    { label: <div id="flags"> <Flag country="ZM"/> &ensp;Zambia </div>, value: 'Zambia (ZMW)' },
    { label: <div id="flags"> <Flag country="ZW"/> &ensp;Zimbabwe </div>, value: 'Zimbabwe (USD)' },

];